language: node_js
node_js:
  - "stable"

env:
 global:
   - GH_REF: github.com/afeiship/next-decimal.git

before_install:
  - chmod 755 ./deploy.sh

install:
  - npm install

script:
  - npm run test

after_success:
  - sh ./deploy.sh
