language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- chmod 755 ./deploy.sh
install:
- npm install
script:
- npm run test
- npm run build
after_script:
- "./deploy.sh"
env:
  global:
    secure: QzgZf6KNOQq7U7Tdu5/gksr+rsCRaU15e/tX9PAvaiw7YCtYGsD1dIdXe46JUS2x3n+S5AK2rYiy/tPl15waHUx6i5Qe3jYwGBa1bybb6L3SE/3qDk9k4qD17JotYOibHjDUl8WOJZVxOAJ+Abox6n+hoLFKndObvjKqWaJS7JalcIRy65M34dvhymyf2lyaEweE3QdiiBRmpPR6DIsd+m8aDtyJ22tTrUXCWtbRWqB7lUDsI1SFasEoRE015c6vvnEDq5YaDvlfWaJFtWcKzd4/PgOfo00pRfRZu9VQK7tSuiVkp9USxlfaLEFUctgggA9yAiQaTdfcXIU1hINGQ0AEriokWW41Yzijc9p+JOwt334hKvPJdJsYfQWSr2kpa9uxqUGU68m8p92O2aDGDTYRt9Zf6euQZK+k2TTPtmWUX9azfUwtlMt6NehCDuN95M+nKpU/AcsCTQvC1si1xTgGF6Ikh76Go+do/6UvHL9unTv7p4Ma8bf/hkDnAMG4w2lmkSsdYcQdZBbg8bjkOHai79k7Yx/VTRWSZ85qhUdSectMQPmFG7xYKDIO+XZQutGu77LKcepZXRRMsb5gJqEPDVcY+usFi/76y0XjKgO8D0sVtCc+OB7Nw7yT+DdiH7jJzfk0MqkRyiu9vp5S2qnmSzp2lPwEKCl2jt9Zoxk=
