language: node_js
node_js:
  - "stable"

# Travis-CI Caching
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - chmod 755 ./deploy.sh

install:
  - npm install

script:
  - npm run test

after_script:
  - ./deploy.sh
