env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8


install:
  - npm install

scripts:
  - npm run test
  - npm run build
